# Issues must be reported only in https://github.com/FreeSoftwareDatabase/fswdb
name: 'Repo Lockdown'

on:
  issues:
    types: opened
  pull_request_target:
    types: opened
  schedule:
    - cron: '0 * * * *'

permissions:
  issues: write
  pull-requests: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/repo-lockdown@v4
        with:
          issue-comment: >
            AUTOMATIC - This repository does not accept bug reports.
            Use /fswdb instead.
          skip-closed-issue-comment: true
          pr-comment: >
            AUTOMATIC - This repository does not accept pull requests.
            Use /fswdb instead.
          skip-closed-pr-comment: true
